### ISSUE TITLE
PHNY 

### ISSUE THREAD

**Issue by JcFl4** [carmichaelalonso/InfiniteFlight-Airports#117]

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/18038538/018980ea-6d5f-11e6-8c0d-29d5f504e1a4.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18038543/17c0d386-6d5f-11e6-8590-1da37ab8beb2.png)

**Comment by dushyants19** [comment]
Airport realigned with WEDbing. Made it as a Class E
