### ISSUE TITLE
KAPV

### ISSUE THREAD

**Issue by JcFl4** [carmichaelalonso/InfiniteFlight-Airports#127]

**Comment by dushyants19** [comment]
@JcFl4 you still doing this?

**Comment by JcFl4** [comment]
No, no. It was closed already.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20868370/86e260ec-ba1f-11e6-9bfe-0d6e5b48b3d1.png)
