### ISSUE TITLE
KPUB

### ISSUE THREAD

**Issue by carmichaelalonso** [carmichaelalonso/InfiniteFlight-Airports#157]
Denver

**Comment by Swang007** [comment]
@kohanson

**Comment by Swang007** [comment]
Has anyone made recent changes to this airport? @kohanson ? There's a bug discussion on the community forum and I decided I was going to fix it. Imported the apt.dat file and turns out it's already fixed...

**Comment by Swang007** [comment]
I guess since it's in the #2 milestone it will come out in the next update.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20866151/023cc0aa-b9eb-11e6-8631-bccf9ca62530.png)
