### ISSUE TITLE
WSAT

### ISSUE THREAD

**Issue by carmichaelalonso** [carmichaelalonso/InfiniteFlight-Airports#172]
Singapore

**Comment by kohanson** [comment]
I am working on this. Anyway to change the tag?

**Comment by jpperks** [comment]
Over to you...

**Comment by kohanson** [comment]
thanks!

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17270530/4b1e3b02-562a-11e6-8fef-15c19a51bcf1.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17912979/c78dc60e-695c-11e6-8b9c-2b1294a4dd6e.png)
