### ISSUE TITLE
KNXP

### ISSUE THREAD

**Issue by carmichaelalonso** [carmichaelalonso/InfiniteFlight-Airports#173]
SoCal

**Comment by kohanson** [comment]
Hi, I want to work on this, how do I change the tag to being redone?

**Comment by Swang007** [comment]
I think they have to make you a collaborator, then you'll be able to change things yourself. I did it for you this time :)

**Comment by kohanson** [comment]
ok noted, thank you very much.

**Comment by kohanson** [comment]
redone completed.

**Comment by kilt46** [comment]
Carrier Simulated Landing Strip added
http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KNXP

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21210313/97413440-c23f-11e6-966e-f490c2b22fc7.png)
