### ISSUE TITLE
ETNN

### ISSUE THREAD

**Issue by carmichaelalonso** [carmichaelalonso/InfiniteFlight-Airports#214]
Amsterdam

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17277580/01408d9a-570c-11e6-9c3f-278fcfc22fed.png)

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/17651530/cbffff02-622e-11e6-98d2-7caaf6a3e0a4.png)
