### ISSUE TITLE
KBMI

### ISSUE THREAD

**Issue by carmichaelalonso** [carmichaelalonso/InfiniteFlight-Airports#225]
Chicago

**Comment by JohnPreston21** [comment]
Sean is doing this one

**Comment by Swang007** [comment]
Changed Spawn Point Names

**Comment by Swang007** [comment]
Working on Curved Taxi line improvements and improved in-game performance by saving object count

**Comment by Swang007** [comment]
Changes submitted. Description attached!

**Comment by Swang007** [comment]
Adding RWY & taxiway shoulders

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21207055/6d462682-c22b-11e6-9d14-a6dd9df29d39.png)
