### ISSUE TITLE
KARR

### ISSUE THREAD

**Issue by carmichaelalonso** [carmichaelalonso/InfiniteFlight-Airports#226]
Chicago

**Comment by Swang007** [comment]
Changed Spawn Point Names

**Comment by Swang007** [comment]
Adding Hold-short markings

**Comment by Swang007** [comment]
Changes submitted. Description attached!

**Comment by Swang007** [comment]
Adding RWY & taxiway shoulders

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/21166129/300a94c8-c169-11e6-9fb5-7759177c7711.png)
