### ISSUE TITLE
KNUC

### ISSUE THREAD

**Issue by carmichaelalonso** [carmichaelalonso/InfiniteFlight-Airports#32]

**Comment by Swang007** [comment]
Will make some minor changes. Taxi lines are currently not lined up, random objects hidden everywhere. Multiple taxiways (when there really should only be one).

**Comment by Swang007** [comment]
...Or I'll do redo the whole thing

**Comment by Swang007** [comment]
Done. Specs in the Submission description.

**Comment by Swang007** [comment]
Will add ATIS frequency

**Comment by Swang007** [comment]
Frequency already in place, move along :)

**Comment by Swang007** [comment]
Finalized for 2015 Milestone 2

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19626085/bbec4750-98ee-11e6-9bf7-4fd310fff236.png)
