### ISSUE TITLE
KNKX

### ISSUE THREAD

**Issue by Nik-Barbour** [carmichaelalonso/InfiniteFlight-Airports#57]
It's going to take a while - but I have to do Miramar

**Comment by carmichaelalonso** [comment]
Nik is taking this.

**Comment by Nik-Barbour** [comment]
Finished

**Comment by Swang007** [comment]
Hey @Nik-Barbour someone gave you a 10/10 rating in IFFG for this one!

**Comment by kilt46** [comment]
Carrier Simulated Landing Strip added
Image: http://kiltmchaggis.com/tikiwiki1/tiki-index.php?page=KNKX

**Comment by dushyants19** [comment]
Spawn Points removed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/20041775/f44c1e90-a433-11e6-8011-db54b4df9d4b.png)

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/53771287-a0381000-3ea7-11e9-8971-39ac643682b5.png)
