### ISSUE TITLE
PHSF

### ISSUE THREAD

**Issue by Nik-Barbour** [carmichaelalonso/InfiniteFlight-Airports#78]
Nik Barbour

**Comment by Nik-Barbour** [comment]
Quickly redone, corrected runways & features, and added spawn and boundary. 
Closed.

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19003453/7413026e-8716-11e6-9c7f-72b6f3044a1b.png)
