### ISSUE TITLE
PHHN

### ISSUE THREAD

**Issue by Nik-Barbour** [carmichaelalonso/InfiniteFlight-Airports#81]

**Comment by Nik-Barbour** [comment]
Corrected features, removed unnecessary lines, added spawns, and boundary, drawn tower building. Closed

**Comment by dushyants19** [comment]
Made more changes and Gated for Global in fbf339db745de49a4c7e26ed8a35e25945846af9

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19055654/bcfa179e-898a-11e6-89a1-b96ed4d3f3a1.png)
