### ISSUE TITLE
PHUP

### ISSUE THREAD

**Issue by Nik-Barbour** [carmichaelalonso/InfiniteFlight-Airports#82]

**Comment by Nik-Barbour** [comment]
Boundary fixed,  additional parking markings, and spawns added. Closed

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19223290/f42601be-8e31-11e6-99dd-2928d1113335.png)

**Comment by MBeringuy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/32115399/71561662-3d2bf100-2a58-11ea-859c-dd4883ee9b5e.jpg)
